---
- name: Create monica user
  ansible.builtin.user:
    name: "{{ monica_container_user }}"
    shell: /sbin/nologin
    create_home: true
    state: present
  become: true

- name: Get created user metadata
  ansible.builtin.getent:
    database: passwd
    key: "{{ monica_container_user }}"

- name: Setting user id and group id facts
  ansible.builtin.set_fact:
    created_uid: "{{ ansible_facts.getent_passwd[monica_container_user].1 }}"
    created_gid: "{{ ansible_facts.getent_passwd[monica_container_user].2 }}"

- name: Ensure monica folders exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ monica_container_user }}"
    group: "{{ monica_container_user }}"
    state: directory
    mode: 0755
  loop:
    - "{{ monica_host_config_path }}"

- name: Ensure monica db folder exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ monica_container_user }}"
    group: "{{ monica_container_user }}"
    state: directory
    mode: 0700
  loop:
    - "{{ monica_host_db_path }}"

- name: Copy monica docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ monica_host_config_path }}/docker-compose.yml"
    owner: "{{ monica_container_user }}"
    group: "{{ monica_container_user }}"
    mode: 0644
  become: true

- name: Create systemd monica service.
  ansible.builtin.template:
    src: templates/monica.service.j2
    dest: "/etc/systemd/system/monica.service"
    mode: 0644
  become: true

- name: Ensure monica.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: monica
  become: true

- name: Check monica container
  ansible.builtin.uri:
    url: "http://localhost:{{ monica_host_port }}"
    status_code: [200, 401]
  register: result
  until: result.status == 200 or result.status == 401
  retries: 5
  delay: 60

- name: Remove old image versions
  become: true
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
